version: '3.8'
services:
  democredit-app:
    build: .
    container_name: demoCredit-app
    ports:
      - '${APP_LOCAL_PORT}:${APP_DOCKER_PORT}'
    environment:
      - NODE_ENV=production
      - DB_HOST=${MYSQLDB_HOST}
      - DB_PORT=${MYSQLDB_USER}
      - DB_USER=${MYSQLDB_USER}
      - DB_PASSWORD=${MYSQLDB_PASSWORD}
      - DB_NAME=${MYSQLDB_DATABASE}
    depends_on:
      - democredit-db

  democredit-db:
    image: mysql:8
    container_name: demoCredit-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_PASSWORD}
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
      MYSQL_USER: ${MYSQLDB_USER}
      MYSQL_PASSWORD: ${MYSQLDB_PASSWORD}
    ports:
      - '${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: